# fly.toml app configuration file generated for bot-be-named-billowing-fog-6159 on 2024-07-17T05:18:38+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bot-be-named-billowing-fog-6159'
primary_region = 'ams'

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_start_machines = true
  auto_stop_machines = false  # prevent automatic suspension
  min_machines_running = 1  # keep a machine running at all times